apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisix-etcd-snapshotter
spec:
  {{ if .Values.config.backupDebug }}
  replicas: 1
  {{ else }}
  replicas: 0
  {{ end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: snapshotter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: snapshotter
    spec:
      containers:
        - name: etcd-snapshotter
          command: [ "sh", "-c"]
          args: ["while true; do echo -n '.' && sleep 10; done;"]
#                - /opt/bitnami/scripts/etcd/snapshot.sh
          env:
            - name: BITNAMI_DEBUG
              value: 'false'
            - name: ETCDCTL_API
              value: '3'
            - name: ETCD_ON_K8S
              value: 'yes'
            - name: MY_STS_NAME
              value: apisix-etcd
            - name: ETCD_CLUSTER_DOMAIN
              value: apisix-etcd-headless.apisix.svc.cluster.local
            - name: ETCD_SNAPSHOT_HISTORY_LIMIT
              value: '3'
          image: docker.io/bitnami/etcd:3.5.4-debian-11-r14
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /snapshots
              name: snapshot-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - name: snapshot-volume
          persistentVolumeClaim:
            claimName: etcd-backup
