basic:
  resource-prefix: aws-zxc-eu
  iam-prefix:
  tags:
    product_code: ZD-ZXC-EU
    product_name: ZD-ZXC-EU
vpc:
  name: test-zk-vpc
  private-az-list:
    - private-a
    - private-b
  public-az-list:
    - private-c


redis:
  create: true
  create-private-subnet-group: true
  create_cloudwatch_log_group: true
  config:
    infix_name: cache
    engine: redis
    engine_version: 6.2
    node_type: cache.m6g.large
    num_cache_clusters: 2


mysql:
  create: true
  create-private-subnet-group: true
  config:
    infix_name: data
    engine: mysql
    engine_version: 8.0.35
    instance_class: db.m5.large
    db_name: ZXC
    backup_retention_period: 7


kafka:
  front:
    create: true
    config:
      kafka_version: 2.8.1
      number_of_broker_nodes: 2
      broker_node_instance_type: kafka.m5.large
      storage_volume_size: 500
      create_configuration: true
      configuration_server_properties: |
        default.replication.factor=2
        min.insync.replicas=1
        log.retention.hours=24
  back:
    create: true
    config:
      kafka_version: 2.8.1
      number_of_broker_nodes: 2
      broker_node_instance_type: kafka.m5.large
      storage_volume_size: 500
      create_configuration: true
      configuration_server_properties: |
        default.replication.factor=2
        min.insync.replicas=1
        log.retention.hours=24   

iam:
  service-role:
    glue:
      S3:
        - a
        - b
flink:
  m241-parse:
    create: true
    config:
      runtime_environment: FLINK-1_13





